# |=================================================
# | Usar MySql?
# |-------------------------------------------------
# | TRUE
# | Se estiver true vai usar MySql e os dados para ligar
# | a base de dados em baixo.
# |
# | FALSE
# | Se estiver false vai usar SQLite para guardar os dados
# | e nao precisa de preencher os dados de conexao
# |-------------------------------------------------
MySql:
  usar: false
  host: localhost
  port: 3306
  database: herospawners
  user: root
  pass: ''
spawn-random: true
juntar:
  raio: 5
  maximo: 0
interact:
  ativar: true
  delay: 2000
  texto:
    - '&5Informações do spawner:'
    - '&r'
    - '&eDono: &7%dono%'
    - '&eStack: &7%quantidade%'
    - '&eMob: &7%tipo%'
    - '&r'
holograma:
  ativar: true
  metodo: "TIMER"
  delay: 20
  distancia: 3
  texto:
    - '&7%quantidade%x &e%tipo%'
    - '&eDono: &7%dono%'
    - '%skull%'
spawner:
  enable: true
  dropXP: false
  allow-break-vanilla-spawners: false
  ItemStack:
    name: '&7Gerador de Monstros'
    lore:
      - '&eTipo: &7%tipo%'
      - '&eQuantidade: &7%quantidade%'
  SilkTouch:
    enable: true
    minLevel: 1
    detroySpawnerWithouSilktouch: true
mobs:
  CREEPER:
    name: Creeper
    head: MHF_Creeper
  SKELETON:
    name: Esqueleto
    head: MHF_Skeleton
  SPIDER:
    name: Aranha
    head: MHF_Spider
  GIANT:
    name: Gigante
    head: MHF_Zombie
  ZOMBIE:
    name: Zombie
    head: MHF_Zombie
  SLIME:
    name: Slime
    head: MHF_Slime
  GHAST:
    name: Ghast
    head: MHF_Ghast
  PIG_ZOMBIE:
    name: PigZombie
    head: MHF_PigZombie
  ENDERMAN:
    name: Enderman
    head: MHF_Enderman
  CAVE_SPIDER:
    name: Aranha da Caverma
    head: MHF_CaveSpider
  SILVERFISH:
    name: Silverfish
    head: MHF_Silverfish
  BLAZE:
    name: Blaze
    head: MHF_Blaze
  MAGMA_CUBE:
    name: Lava Slime
    head: MHF_LavaSlime
  ENDER_DRAGON:
    name: Dragao
    head: LandM
  WITHER:
    name: Wither
    head: MHF_WitherBoss
  BAT:
    name: Bat
    head: MHF_Bat
  WITCH:
    name: Bruxa
    head: MHF_Witch
  ENDERMITE:
    name: Endermite
    head: MHF_Endermite
  GUARDIAN:
    name: Guardian
    head: MHF_Guardian
  PIG:
    name: Porco
    head: MHF_Pig
  SHEEP:
    name: Ovelha
    head: MHF_Sheep
  COW:
    name: Vaca
    head: MHF_Cow
  CHICKEN:
    name: Galinha
    head: MHF_Chicken
  SQUID:
    name: Polvo
    head: MHF_Squid
  WOLF:
    name: Lobo
    head: MHF_Wolf
  MUSHROOM_COW:
    name: Cogu Vaca
    head: MHF_MushroomCow
  SNOWMAN:
    name: SnowMan
    head: MHF_SnowGolem
  OCELOT:
    name: Ocelot
    head: MHF_Ocelot
  IRON_GOLEM:
    name: Iron Golem
    head: MHF_Golem
  HORSE:
    name: Cavalo
    head: MHF_Horse
  RABBIT:
    name: Coelho
    head: MHF_Rabbit
  VILLAGER:
    name: Villager
    head: MHF_Villager
